import { BarChart3, Braces, Database, FlaskConical, ShieldAlert } from 'lucide-react'
import type { ModelInfo } from '../types'
import { Panel } from './ui'

export default function ModelLab({ model }: { model: ModelInfo }) {
  return <div className="model-view">
    <div className="model-intro"><FlaskConical size={30} /><div><h2>Real models. Synthetic evidence.</h2><p>Both classifiers train locally at API startup. Their results are reproducible, inspectable, and limited by the synthetic data.</p></div><span className="mono">seed {model.seed}</span></div>
    <div className="model-metrics"><div><span>Telemetry ROC-AUC</span><strong>{model.roc_auc.toFixed(3)}</strong><small>Held-out synthetic players</small></div><div><span>Telemetry F1</span><strong>{model.f1.toFixed(3)}</strong><small>At a 0.50 classifier threshold</small></div><div><span>Brier score</span><strong>{model.brier_score.toFixed(3)}</strong><small>Lower is better; synthetic only</small></div><div><span>Chat macro F1</span><strong>{model.nlp.macro_f1.toFixed(3)}</strong><small>Held-out template families</small></div></div>
    <div className="model-grid"><Panel title="Behavioral classifier" icon={BarChart3}><p className="model-algorithm">{model.algorithm}</p><p className="panel-description">A learned probabilistic classifier predicts a stochastic synthetic risk target from eight telemetry features. The target is sampled from latent behavioral stress in the simulator.</p>
      <div className="training-split"><div><span>Training</span><strong>{model.train_windows.toLocaleString()} windows</strong><small>{model.train_players} player identities</small></div><div><span>Evaluation</span><strong>{model.test_windows.toLocaleString()} windows</strong><small>{model.test_players} different identities</small></div></div>
      <h3 className="small-heading">Standardized coefficient magnitude</h3><p className="fine-print left">Relative model weights; these are not causal importance.</p><div className="feature-weights">{[...model.features].sort((a, b) => b.importance - a.importance).map(feature => <div key={feature.name}><span>{feature.label}</span><div><i style={{ width: `${feature.importance * 400}%` }} /></div><span className="mono">{Math.round(feature.importance * 100)}%</span></div>)}</div>
    </Panel><Panel title="Chat classifier" icon={Braces}><p className="model-algorithm">{model.nlp_algorithm}</p><p className="panel-description">Neutral, frustrated and toxic language are learned from hand-authored English examples. Risk = P(toxic) + 0.45 × P(frustrated). This weight is visible demo policy.</p><div className="training-split"><div><span>Training</span><strong>{model.nlp.train_messages} messages</strong><small>{model.nlp.train_templates} templates</small></div><div><span>Evaluation</span><strong>{model.nlp.test_messages} messages</strong><small>{model.nlp.test_templates} unseen templates</small></div></div>
      <h3 className="small-heading">Telemetry confusion matrix</h3><p className="fine-print left">Rows: true label · Columns: predicted label</p><table className="confusion-table"><thead><tr><th>Actual / predicted</th><th>Lower risk</th><th>Elevated risk</th></tr></thead><tbody>{model.confusion_matrix.map((row, i) => <tr key={i}><th>{i ? 'Elevated risk' : 'Lower risk'}</th>{row.map((value, j) => <td className={i === j ? 'mint-text' : ''} key={j}>{value}</td>)}</tr>)}</tbody></table><p className="fine-print left">Classifier evaluation threshold (50) differs from UI risk bands (35 / 65). Neither threshold has been validated on real telemetry.</p>
    </Panel></div>
    <Panel title="Evidence boundaries" icon={ShieldAlert} className="limitations-panel"><ul>{model.limitations.map(l => <li key={l}>{l}</li>)}</ul></Panel>
    <Panel title="Reproduce this run" icon={Database} className="repro-panel"><div><span>Dataset fingerprint</span><code>{model.dataset_fingerprint}</code></div><div><span>Model version</span><code>{model.version}</code></div><div><span>Generate evaluation</span><code>python -m backend.train</code></div><p className="fine-print left">Split: {model.split}. Data and model fits use fixed seed {model.seed}; no API keys or network calls are needed for inference.</p></Panel>
  </div>
}
